### ISSUE TITLE
New MUC++ logo

### ISSUE THREAD

**Issue by Voultapher** [MUCpp/logo#1]
This is the tracking issue for all things related to the new MUC++ logo.

Please post your suggestions as comments here. Attach your proposal images to your comment, so that everyone can directly see them. [See this for help](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

There will be **no** voting yet, still feel free to leave reactions to proposals.

---

Our current Meetup logo is the commonly used [isocpp C++ logo](https://github.com/isocpp/logos). We want to create a unique logo that reflects our usergroup and what it is about.

It should have these properties:
- Unique
- Clearly recognizable, even at small resolutions like 32x32
- Square and works even when corners aren't visible

Your proposal should include:
- icon 32x32
- icon 128x128
- icon 1024x1024 or more
- banner with aspect ration 3:1 3072x1024 or more

**Comment by Voultapher** [comment]
Proposal by Klaus Iglberger:

- Icon 32x32

![klaus_32_1_0](https://user-images.githubusercontent.com/6864584/50740471-45f43900-11ef-11e9-8966-1dbbe48ee3b2.png)

- Icon 128x128

![klaus_mucpp](https://user-images.githubusercontent.com/6864584/40269984-f105fdea-5b85-11e8-8475-b45acb33ccb0.png)

- Icon 1024x1024

![muc_logo_blau_e2](https://user-images.githubusercontent.com/6864584/40270209-3c640928-5b89-11e8-8c97-aae3895bce50.png)

- Banner 3072x1024

![muc_logo_blau_banner_e2](https://user-images.githubusercontent.com/6864584/40270210-40532fbe-5b89-11e8-9325-70c3e9d5d9e9.png)

**Comment by Voultapher** [comment]
My proposal:

- Icon 32x32

![old_32_1_01](https://user-images.githubusercontent.com/6864584/50740488-70de8d00-11ef-11e9-97fb-53f76bb173b5.png)

- Icon 128x128

![mucpp](https://user-images.githubusercontent.com/6864584/40270257-e1c56fa6-5b89-11e8-8c9f-684a5452aeb5.png)

- Icon 1024x1024

![icon7_04_e1](https://user-images.githubusercontent.com/6864584/40270244-b30c7ff6-5b89-11e8-930f-90de2df79682.png)

- Banner 3072x1024

![icon7banner1_04_e1](https://user-images.githubusercontent.com/6864584/40270246-c0dd4ca0-5b89-11e8-93e7-9d28f8e4fd95.png)

**Comment by Voultapher** [comment]
My second proposal:

- Icon 32x32

![combined_32_1_01](https://user-images.githubusercontent.com/6864584/50740500-a71c0c80-11ef-11e9-88e4-5b2957c5eb78.png)

- Icon 128x128

![combined_128_1_01](https://user-images.githubusercontent.com/6864584/50740505-b307ce80-11ef-11e9-9bd8-831a684b2977.png)

- Icon 1024x1024

![combined_1024_1_01](https://user-images.githubusercontent.com/6864584/50740506-ba2edc80-11ef-11e9-887c-120a07d313a9.png)

- Banner 3072x1024

![banner_3072_1_01](https://user-images.githubusercontent.com/6864584/50740509-bf8c2700-11ef-11e9-9026-4490984e4ad0.png)

**Comment by igl42** [comment]
Another proposal with a Bavarian touch:

- Icon 32x32
![32x32--c](https://user-images.githubusercontent.com/31173856/51979615-e0ae0380-248d-11e9-95ea-b7c17dc96b1f.png)

- Icon 128x128
![128x128--c](https://user-images.githubusercontent.com/31173856/51979621-e73c7b00-248d-11e9-8c22-41a0f0ff1135.png)

- Icon 1024x1024
![1024x1024--c](https://user-images.githubusercontent.com/31173856/51979630-edcaf280-248d-11e9-9b58-50240395abd1.png)

- Banner 3072x1024
![3072x1024](https://user-images.githubusercontent.com/31173856/51979651-fa4f4b00-248d-11e9-8e5c-40e6445671a5.png)
